server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/online_business_user?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

dubbo:
  application:
    name: user-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 26880
  provider:
    timeout: 3000
    retries: 0

logging:
  level:
    root: INFO
